version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangotube/:/usr/src/djangotube/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=djangotube
      - POSTGRES_PASSWORD=djangotubep@$$w0rd
      - POSTGRES_DB=djangotube

volumes:
  postgres_data: